name: main 
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.2

# Add regular dependencies here.
dependencies:

dev_dependencies:
  test: ^1.21.0
  very_good_analysis: ^5.1.0

executables:
  repo:
    path: bin/main.dart
